#!/bin/bash

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

# Try auto install for composer
if [ -f "$WEBROOT/composer.lock" ]; then
  php composer.phar install --no-dev
fi

cd /var/www/html
git pull || exit 1
chown -Rf nginx:nginx /var/www/html
